kind: pipeline
name: plugin-tag

trigger:
  branch:
    - plugin

platform:
  os: linux
  arch: amd64

steps:
  - name: plugin-zip
    image: docker
    commands:
    - cd ..
    - mkdir -p plugins/opni-dashboards-plugin
    - mv src/* plugins/opni-dashboards-plugin
    - git clone -b 1.3 --single-branch https://github.com/opensearch-project/OpenSearch-Dashboards.git
    - ls
