kind: pipeline
name: plugin-tag

trigger:
  event: 
    - tag
  branch:
    - plugin

platform:
  os: linux
  arch: amd64

steps:
  - name: plugin-clone
    image: alpine/git
    commands:
      - cd ..
      - git clone -b 2.4 --single-branch https://github.com/opensearch-project/OpenSearch-Dashboards.git OpenSearch-Dashboards
      - mkdir -p OpenSearch-Dashboards/plugins/monty-dashboards-plugin
      - mv src/* OpenSearch-Dashboards/plugins/monty-dashboards-plugin
      - mv OpenSearch-Dashboards src/OpenSearch-Dashboards
  - name: plugin-replace-versions
    image: node:14.20.0
    commands:
    - cd OpenSearch-Dashboards/plugins/monty-dashboards-plugin
    - sed -i "s/{VERSION}/${DRONE_TAG/plugin-/}/g" package.json opensearch_dashboards.json
  - name: plugin-build
    image: node:14.20.0
    commands: 
    # The reason for the user/su usage is because opensearch plugins disallow you 
    # from using root when building and by default we're executing as root
    - printf "justauselesspword\njustauselesspword\ny\n" | adduser osd
    - echo "y\n"
    - usermod -aG sudo osd
    - chmod -R 777 OpenSearch-Dashboards
    - cd OpenSearch-Dashboards
    - su -c "yarn osd bootstrap" osd
    - cd plugins/monty-dashboards-plugin
    - su -c "yarn install" osd
    - su -c "yarn build" osd
    - su -c "mv build/*.zip build/monty-dashboards-plugin-${DRONE_TAG/plugin-/}.zip" osd
  - name: plugin-upload-zip
    image: plugins/github-release
    pull: always
    settings:
     overwrite: true
     api_key:
       from_secret: github_token
     files:
       - "OpenSearch-Dashboards/plugins/monty-dashboards-plugin/build/*.zip"

