kind: pipeline
name: plugin-tag

trigger:
  event:
  - tag
  ref:
  - "refs/tags/plugin-*"

platform:
  os: linux
  arch: amd64

steps:
- name: plugin-zip
  commands:
  - echo "test"
---
kind: pipeline
name: docker-tag

trigger:
  event:
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: docker-image
  image: plugins/docker
  settings:
    dockerfile: product/opni/Dockerfile
    tag: ${DRONE_TAG}
    repo: rancher/opni-ui
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
