kind: pipeline
name: plugin-tag

trigger:
  branch:
    - plugin

platform:
  os: linux
  arch: amd64

steps:
  - name: plugin-clone
    image: alpine/git
    commands:
      - printf "justauselesspword\njustauselesspword" | adduser osd
      - su osd
      - cd ..
      - git clone -b 1.3 --single-branch https://github.com/opensearch-project/OpenSearch-Dashboards.git OpenSearch-Dashboards
      - mkdir -p OpenSearch-Dashboards/plugins/opni-dashboards-plugin
      - mv src/* OpenSearch-Dashboards/plugins/opni-dashboards-plugin
  - name: plugin-zip
    image: node:10
    commands:
    - su osd
    - cd OpenSearch-Dashboards
    - yarn osd bootstrap
    - cd plugins/opni-dashboards-plugin
    - yarn install
    - ls node_modules/@osd
