kind: pipeline
name: plugin-tag

trigger:
  branch:
    - plugin

platform:
  os: linux
  arch: amd64

steps:
  - name: plugin-zip
    image: docker
    commands:
    - cd ..
    - mkdir -p plugins/opni-dashboards-plugin
    - mv src/* plugins/opni-dashboards-plugin
    - ls plugins/opni-dashboards-plugin
