kind: pipeline
name: plugin-tag

trigger:
  event: 
    - tag
  branch:
    - plugin

platform:
  os: linux
  arch: amd64

steps:
  - name: plugin-upload-zip
    image: plugins/github-release
    pull: always
    settings:
     overwrite: true
     api_key:
      from_secret: github_token
     files:
     - "package.json"
  - name: plugin-clone
    image: alpine/git
    commands:
      - cd ..
      - git clone -b 1.3 --single-branch https://github.com/opensearch-project/OpenSearch-Dashboards.git OpenSearch-Dashboards
      - mkdir -p OpenSearch-Dashboards/plugins/opni-dashboards-plugin
      - mv src/* OpenSearch-Dashboards/plugins/opni-dashboards-plugin
      - mv OpenSearch-Dashboards src/OpenSearch-Dashboards
  - name: plugin-build
    image: node:10
    commands:
    - echo ${DRONE_TAG}
    - echo ${DRONE_TAG/plugin-/}
    - printf "justauselesspword\njustauselesspword\ny\n" | adduser osd
    - echo "y\n"
    - usermod -aG sudo osd
    - chmod -R 777 OpenSearch-Dashboards
    - cd OpenSearch-Dashboards
    - su -c "yarn osd bootstrap" osd
    - cd plugins/opni-dashboards-plugin
    - su -c "yarn install" osd
    - su -c "yarn build" osd
    - su -c "ls build" osd

