name: Plugin and Docker Build on Tag

on:
  push:
    tags:
      - '*'
    branches:
      - plugin
      - main

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && github.ref_name == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: product/monty/Dockerfile
          push: true
          tags: rancher/monty-ui:${{ steps.extract_tag.outputs.tag }}
          platforms: linux/amd64